### ISSUE TITLE
linux/aarch64 support

### ISSUE THREAD

**Issue by mbogner** [valkey-io/valkey-container#13]
any reason not to offer an aarch64 image for apple users?

building on my mac m1 works:

```Dockerfile
FROM debian
ARG VERSION=7.2.5-rc1

RUN useradd -ms /bin/bash valkey
WORKDIR /home/valkey

# install prerequisites
RUN apt update &&\
    apt install -y build-essential pkg-config wget &&\
    rm -rf /var/lib/apt/lists/*

# install from source
RUN wget https://github.com/valkey-io/valkey/archive/refs/tags/${VERSION}.tar.gz -O valkey-${VERSION}.tgz &&\
    tar -xf valkey-${VERSION}.tgz

RUN cd valkey-${VERSION} &&\
    make &&\
    make install

USER valkey
```

```shell
docker build --platform=linux/aarch64 -f Dockerfile -t valkey/custom-aarch64:latest .
docker build --platform=linux/amd64 -f Dockerfile -t valkey/custom-amd64:latest .
```

With some manifest amends it would therefor be easy to have image support. Same could be done with alpine or other base images instead of debian.

Of course I could create some custom images and upload them to dockerhub but i would rather prefer having some from the real project. I am not 100% familiar with the workflow you're using to generate the existing images but in case you need extra hands let me know.

**Comment by darkorb** [comment]
The `linux/arm64` build works perfectly well on my M1 (plus, also Oracle Cloud).

https://hub.docker.com/r/valkey/valkey/tags

Even shows `aarch64` if you check inside the container. Did you get errors? I can try with the image version you tested with if so.

**Comment by mbogner** [comment]
didn't work when i tried. now it works.

```shell
docker run -ti --rm valkey/valkey:7.2
```
