### ISSUE TITLE
Accept start arguments through ENV variable

### ISSUE THREAD

**Issue by aliismayilov** [valkey-io/valkey-container#18]
In an environment like Github Actions it is not possible to modify the start command of [services](https://docs.github.com/en/actions/using-containerized-services/about-service-containers). So, the only way to run valkey with different server configuration would be to maintain a derived docker image where the default CMD is overwritten or custom `valkey.conf` is packaged.

It would be great to be able to pass start arguments to `valkey-server` through an environment variable and keep using the official image.

For reference, I like how [ubuntu/redis image](https://hub.docker.com/r/ubuntu/redis) has it through `REDIS_EXTRA_FLAGS` env variable. I'd be happy to submit a pull request if maintainers agree to the suggestion.

**Comment by muntdan** [comment]
Any update on this ?

**Comment by stockholmux** [comment]
@roshkhatri Any thoughts on this one?

**Comment by roshkhatri** [comment]
Yes, this seems to be a great idea to enable passing flags to `valkey-server` through `VALKEY_EXTRA_FLAGS`.

Sorry I could not get to this earlier.

@aliismayilov, you are more than welcome to submit a PR.

**Comment by aliismayilov** [comment]
> Yes, this seems to be a great idea to enable passing flags to `valkey-server` through `VALKEY_EXTRA_FLAGS`.
> 
> Sorry I could not get to this earlier.
> 
> @aliismayilov, you are more than welcome to submit a PR.

Thanks for looking into it! You can check the PR when you have time 🙏 https://github.com/valkey-io/valkey-container/pull/41

**Comment by roshkhatri** [comment]
Thank you so much!

**Comment by muntdan** [comment]
It seams that on windows CMD the ' needs to be " for the arguments:
`docker run -e VALKEY_EXTRA_FLAGS='--save 60 1 --loglevel warning' valkey/valkey`
